export const TOGGLE_DRAWER = "TOGGLE_DRAWER"


// core team form actions 
export const CORE_TEAM_NAME_CHANGE = "CORE_TEAM_NAME_CHANGE"
export const CORE_TEAM_POSITION_CHANGE = "CORE_TEAM_POSITION_CHANGE"
export const CORE_TEAM_EMAIL_CHANGE = "CORE_TEAM_EMAIL_CHANGE"
export const CORE_TEAM_GITHUB_CHANGE = "CORE_TEAM_GITHUB_CHANGE"
export const CORE_TEAM_LINKEDIN_CHANGE = "CORE_TEAM_LINKEDIN_CHANGE"
export const SUBMIT_CORE_TEAM_FORM = "SUBMIT_CORE_TEAM_FORM"